import { Paginator } from "@pantheon-systems/nextjs-kit";
import { NextSeo } from "next-seo";
import Layout from "../../components/layout";
import PageHeader from "../../components/page-header";
import { ArticleGrid } from "../../components/article-grid";
import { getAllArticles } from "../../lib/Articles";

export default function ArticlesListTemplate({ articles }) {
  return (
    <Layout>
      <NextSeo
        title="Decoupled Next PCC Demo"
        description="Generated by create-pantheon-decoupled-kit."
      />
      <section>
        <PageHeader title="Articles" />
        <ArticleGrid articles={articles} headingLevel="h2" />
      </section>
    </Layout>
  );
}

export async function getServerSideProps() {
  const articles = await getAllArticles();

  return {
    props: {
      articles,
    },
  };
}
