import { NextSeo } from "next-seo";
import Layout from "../components/layout";
import PageHeader from "../components/page-header";

export default function About() {
  return (
    <Layout>
      <NextSeo
        title="Decoupled Next PCC Demo"
        description="Generated by create-pantheon-decoupled-kit."
      />
      
      <section>
        <PageHeader title="Pantheon Content Cloud for Gov" />
		<p>
			This site is a demo of Pantheon Content Cloud tailored for a government city, state, or agency use case. 
		</p>
		<h4>Design Notes</h4>
		<ul>
			<li>
			The site UX comes from the <a href="https://live-pds-toolkit-react.appa.pantheon.site/?path=/docs/introduction--docs">Pantheon Design System (PDS) React Toolkit</a>.
			</li>
			<li>
			The <a href="https://github.com/540co/govicons">Gov Icons</a> open source font library is used.
			</li>
		</ul>

      </section>
    </Layout>
  );
}
