import { NextSeo } from "next-seo";
import Image from "next/image";
import { PostGrid } from "../components/grid";
import Layout from "../components/layout";
import { getAllArticles } from "../lib/Articles";
import { pdsConfig } from "../pds.config";

export default function Home({ articles }) {
  const HomepageHeader = () => (
    <div className="flex flex-col mx-auto mt-20 prose sm:prose-xl max-w-fit">
      <h1 className="h-full text-4xl prose text-center">Welcome</h1>
    </div>
  );

  return (
    <Layout>
      <NextSeo
        title={pdsConfig.siteName}
        description="Generated by Pantheon Content Cloud"
      />
      <HomepageHeader />
      <section>
        <PostGrid contentType="posts" data={articles} />
      </section>
    </Layout>
  );
}

export async function getServerSideProps() {
  const articles = await getAllArticles();

  return {
    props: {
      articles,
    },
  };
}
